library(networksS17)
library(data.table)

# primary <- gdata::read.xls(
#   "inst/extdata/House_primary_elections_(1956-2010)_data_(pettigrew).xlsx")
# setDT(primary)
# primary_DT <- primary[year < 2008, ]
#
# # make name variables look alike
# primary_DT[, candidate := gsub("_.*", "", candidate)]
# primary_DT[, candidate := toupper(candidate)]
# primary_DT[, candidate := gsub(" ", "", candidate)]
# primary_DT[, incname := gsub(",.*", "", incname)]
# primary_DT[, incname := gsub(" ", "", incname)]
#
# primary_DT <- primary_DT[candidate != incname, ]
# primary_DT <- primary_DT[fr != 9, ]
# primary_DT <- primary_DT[seat <= 1, ]
# primary_DT <- primary_DT[seat == party, ]
# # primary_DT <- primary_DT[inc == 0, ]
# # primary_DT <- primary_DT[qual != 2, ]
# primary_DT <- primary_DT[winner == 1, ]
#
# # errors in names remain
# primary_DT[candidate == "HERBERT" & state == "louisia", candidate := "HEBERT"]
# primary_DT[candidate == "WINDALL" & state == "new jer", candidate := "WIDNALL"]
# primary_DT[candidate == "ST." & state == "new yor", candidate := "ST.GEORGE"]
# primary_DT[candidate == "ST." & state == "connect", candidate := "ST.ONGE"]
# primary_DT[candidate == "ST." & state == "rhode i", candidate := "ST.GERMAIN"]
# primary_DT[candidate == "VAN" & state == "pennsyl", candidate := "VANZANDT"]
# primary_DT[candidate == "VAN" & state == "wiscons", candidate := "VANPELT"]
# primary_DT[candidate == "VAN" & state == "califor", candidate := "VANDEERLIN"]
# primary_DT[candidate == "KIDLAY" & state == "texas", candidate := "KILDAY"]
# primary_DT[candidate == "O" & state == "wiscons", candidate := "O'KONSKI"]
# primary_DT[candidate == "LENSINSKI" & state == "michiga", candidate := "LESINSKI"]
# primary_DT[candidate == "ANDERSON" & state == "minneso", candidate := "ANDERSEN"]
# primary_DT[candidate == "FRELINHUYSEN" & state == "new jer", candidate := "FRELINGHUYSEN"]
# primary_DT[candidate == "LENNNON" & state == "north c", candidate := "LENNON"]
# primary_DT[candidate == "JENNNINGS" & state == "virgini", candidate := "JENNINGS"]
# primary_DT[candidate == "OKANSKI" & state == "wiscons", candidate := "O'CONSKI"]
# primary_DT[candidate == "MILER" & state == "califor", candidate := "MILLER"]
# primary_DT[candidate == "DOWALSKI" & state == "connect", candidate := "KOWALSKI"]
# primary_DT[candidate == "COLLIER,HAROLD" & state == "illinoi", candidate := "COLLIER"]
# primary_DT[candidate == "COHELAND" & state == "califor", candidate := "COHELAN"]
# primary_DT[candidate == "EBENNETT" & state == "florida", candidate := "BENNETT"]
# primary_DT[candidate == "MATTIN" & state == "montana", candidate := "BATTIN"]
# primary_DT[candidate == "SCHWIEKER" & state == "pennsyl", candidate := "SCHWEIKER"]
# primary_DT[candidate == "KOLGORE" & state == "texas", candidate := "KILGORE"]
# primary_DT[candidate == "CHAMERLAIN" & state == "michiga", candidate := "CHAMBERLAIN"]
# primary_DT[candidate == "ROBBERTS" & state == "texas", candidate := "ROBERTS"]
# primary_DT[candidate == "ABERNATHY" & state == "mississ", candidate := "ABERNETHY"]
# primary_DT[candidate == "WHITTIN" & state == "mississ", candidate := "WHITTEN"]
# primary_DT[candidate == "DE" & state == "texas", candidate := "DELAGARZA"]
# primary_DT[candidate == "LAUNDRUM" & state == "georgia", candidate := "LANDRUM"]
# primary_DT[candidate == "FINDELY" & state == "illinoi", candidate := "FINDLEY"]
# primary_DT[candidate == "DONAHUE" & state == "massach", candidate := "DONOHUE"]
# primary_DT[candidate == "ONEILL" & state == "massach", candidate := "O'NEILL"]
# primary_DT[candidate == "VANDER" & state == "michiga", candidate := "VANDERJAGT"]
# primary_DT[candidate == "WHITEEN" & state == "mississ", candidate := "WHITTEN"]
# primary_DT[candidate == "ROBINSON" & state == "new yor", candidate := "ROBISON"]
# primary_DT[candidate == "HECKHLER" & state == "west vi", candidate := "HECHLER"]
# primary_DT[candidate == "KASTANMEIER" & state == "wiscons", candidate := "KASTENMEIER"]
# primary_DT[candidate == "CROSS" & state == "iowa", candidate := "GROSS"]
# primary_DT[candidate == "BEYSEY" & state == "califor", candidate := "VEYSEY"]
# primary_DT[candidate == "ROSTENKOSWKI" & state == "illinoi", candidate := "ROSTENKOWSKI"]
# primary_DT[candidate == "SPEND" & state == "south c", candidate := "SPENCE"]
# primary_DT[candidate == "MCCCLOSKEY" & state == "califor", candidate := "MCCLOSKEY"]
# primary_DT[candidate == "BURKET" & state == "florida", candidate := "BURKE"]
# primary_DT[candidate == "BARNETT" & state == "pennsyl", candidate := "BARRETT"]
# primary_DT[candidate == "HAMMERSCHIDT" & state == "arkansa", candidate := "HAMMERSCHMIDT"]
# primary_DT[candidate == "THORTON" & state == "arkansa", candidate := "THORNTON"]
# primary_DT[candidate == "EDWRADS" & state == "califor", candidate := "EDWARDS"]
# primary_DT[candidate == "SYMM" & state == "idaho", candidate := "SYMMS"]
# primary_DT[candidate == "ANNUNIZO" & state == "illinoi", candidate := "ANNUNZIO"]
# primary_DT[candidate == "ANBRO" & state == "new yor", candidate := "AMBRO"]
# primary_DT[candidate == "COUGLIN" & state == "pennsyl", candidate := "COUGHLIN"]
# primary_DT[candidate == "PRICHARD" & state == "washing", candidate := "PRITCHARD"]
# primary_DT[candidate == "STAGELAND" & state == "minneso", candidate := "STANGELAND"]
# primary_DT[candidate == "MARRIOT" & state == "utah", candidate := "MARRIOTT"]
# primary_DT[candidate == "SILIJANDER" & state == "michiga", candidate := "SILJANDER"]
# primary_DT[candidate == "BILRAKIS" & state == "florida", candidate := "BILIRAKIS"]
# primary_DT[candidate == "HILLER" & state == "indiana", candidate := "HILER"]
# primary_DT[candidate == "IRELAND,ANDREW" & state == "florida", candidate := "IRELAND"]
# primary_DT[candidate == "MOTGOMERY" & state == "mississ", candidate := "MONTGOMERY"]
# primary_DT[candidate == "BUSTAMENTE" & state == "texas", candidate := "BUSTAMANTE"]
# primary_DT[candidate == "OWNES" & state == "utah", candidate := "OWENS"]
# primary_DT[candidate == "LPINSKI" & state == "illinoi", candidate := "LIPINSKI"]
# primary_DT[candidate == "TORRICELLLI" & state == "new jer", candidate := "TORRICELLI"]
# primary_DT[candidate == "ENGELL" & state == "new yor", candidate := "ENGEL"]
# primary_DT[candidate == "SOLOMAN" & state == "new yor", candidate := "SOLOMON"]
# primary_DT[candidate == "ROHRABACKER" & state == "califor", candidate := "ROHRABACHER"]
# primary_DT[candidate == "BACCUS" & state == "florida", candidate := "BACCHUS"]
# primary_DT[candidate == "OLIVER" & state == "massach", candidate := "OLVER"]
# primary_DT[candidate == "EPSY" & state == "mississ", candidate := "ESPY"]
# primary_DT[candidate == "SMOTH" & state == "new jer", candidate := "SMITH"]
# primary_DT[candidate == "SCIFF" & state == "new mex", candidate := "SCHIFF"]
# primary_DT[candidate == "MCMILLIAN" & state == "north c", candidate := "MCMILLAN"]
# primary_DT[candidate == "WAHINGTON" & state == "texas", candidate := "WASHINGTON"]
# primary_DT[candidate == "BECETTA" & state == "califor", candidate := "BECERRA"]
# primary_DT[candidate == "BARLETT" & state == "marylan", candidate := "BARTLETT"]
# primary_DT[candidate == "ZEILFF" & state == "new ham", candidate := "ZELIFF"]
# primary_DT[candidate == "SERRAON" & state == "new yor", candidate := "SERRANO"]
# primary_DT[candidate == "MEZVINSKI" & state == "pennsyl", candidate := "MARGOLIES-MEZVINSKI"]
# primary_DT[candidate == "MCDONALD" & state == "califor", candidate := "MILLENDER-MCDONALD"]
# primary_DT[candidate == "CHENOWTH" & state == "idaho", candidate := "CHENOWETH"]
# primary_DT[candidate == "NEHERCUTT" & state == "washing", candidate := "NETHERCUTT"]
# primary_DT[candidate == "OBESTAR" & state == "minneso", candidate := "OBERSTAR"]
# primary_DT[candidate == "LATOURETT" & state == "ohio", candidate := "LATOURETTE"]
# primary_DT[candidate == "BYANT" & state == "tenness", candidate := "BRYANT"]
# primary_DT[candidate == "CALLAHAN,HERBERTL" & state == "alabama", candidate := "CALLAHAN"]
# primary_DT[candidate == "EVERETT,TERRY" & state == "alabama", candidate := "EVERETT"]
# primary_DT[candidate == "RILEY,BOB" & state == "alabama", candidate := "RILEY"]
# primary_DT[candidate == "ADERHOLT,ROBERTBROWN" & state == "alabama", candidate := "ADERHOLT"]
# primary_DT[candidate == "CRAMER,ROBERTE'BUD'" & state == "alabama", candidate := "CRAMER"]
# primary_DT[candidate == "BACHUS,SPENCERTIII" & state == "alabama", candidate := "BACHUS"]
# primary_DT[candidate == "HILLIARD,EARLFREDERICK" & state == "alabama", candidate := "HILLIARD"]
# primary_DT[candidate == "YOUNG,DONALD" & state == "alaska", candidate := "YOUNG"]
# primary_DT[candidate == "PASTOR,EDWARDL" & state == "arizona", candidate := "PASTOR"]
# primary_DT[candidate == "STUMP,BOB" & state == "arizona", candidate := "STUMP"]
# primary_DT[candidate == "SHADEGG,JOHNBARDEN" & state == "arizona", candidate := "SHADEGG"]
# primary_DT[candidate == "KOLBE,JAMEST" & state == "arizona", candidate := "KOLBE"]
# primary_DT[candidate == "HAYWORTH,JD" & state == "arizona", candidate := "HAYWORTH"]
# primary_DT[candidate == "BERRY,MARION" & state == "arkansa", candidate := "BERRY"]
# primary_DT[candidate == "SNYDER,VICTORFREDERICK" & state == "arkansa", candidate := "SNYDER"]
# primary_DT[candidate == "HUTCHINSON,ASA" & state == "arkansa", candidate := "HUTCHINSON"]
# primary_DT[candidate == "DICKEY,JAYWJR" & state == "arkansa", candidate := "DICKEY"]
# primary_DT[candidate == "ESCHOO" & state == "califor", candidate := "ESHOO"]
# primary_DT[candidate == "CATLE" & state == "delawar", candidate := "CASTLE"]
# primary_DT[candidate == "NORWODD" & state == "georgia", candidate := "NORWOOD"]
# primary_DT[candidate == "GILLMORE" & state == "ohio", candidate := "GILLMOR"]
# primary_DT[candidate == "CRENWSHAW" & state == "florida", candidate := "CRENSHAW"]
# primary_DT[candidate == "DAVID" & state == "florida", candidate := "DAVIS"]
# primary_DT[candidate == "ABERCROMIE" & state == "hawaii", candidate := "ABERCROMBIE"]
# primary_DT[candidate == "MEMENDEZ" & state == "new jer", candidate := "MENENDEZ"]
# primary_DT[candidate == "SCHUSTER" & state == "pennsyl", candidate := "SHUSTER"]
# primary_DT[candidate == "MILLENDER" & state == "califor", candidate := "MILLENDER-MCDONALD"]
# primary_DT[candidate == "CARIN" & state == "marylan", candidate := "CARDIN"]
# primary_DT[candidate == "BOEKSTRA" & state == "michiga", candidate := "HOEKSTRA"]
# primary_DT[candidate == "RAYLOR" & state == "mississ", candidate := "TAYLOR"]
# primary_DT[candidate == "MACDONALT" & state == "massach", candidate := "MACDONALD"]
# primary_DT[candidate == "STUCKY" & state == "georgia", candidate := "STUCKEY"]
# primary_DT[candidate == "O'CONSKI" & state == "wiscons", candidate := "O'KONSKI"]
# primary_DT[candidate == "PICINSKI" & state == "illinoi", candidate := "PUCINSKI"]
# primary_DT[candidate == "RIVER" & state == "south c", candidate := "RIVERS"]
# primary_DT[candidate == "DAVID" & state == "illinoi", candidate := "DAVIS"]
# primary_DT[candidate == "MEZVINSKY" & state == "pennsyl", candidate := "MARGOLIES-MEZVINSKI"]
# primary_DT[candidate == "VANDERJAGT" & state == "michiga", candidate := "VANDERVEEN"]
#
# primary_DT[incname == "WAGGONER" & state == "louisia", incname := "WAGGONNER"]
# primary_DT[incname == "DAVIS_JAMES" & state == "georgia", incname := "DAVIS"]
# primary_DT[incname == "MONTOYA_JOSEPH" & state == "new mex", incname := "MONTOYA"]
# primary_DT[incname == "PETERSON_BLAINE" & state == "utah", incname := "PETERSON"]
# primary_DT[incname == "BEGICH_NICK" & state == "alaska", incname := "BEGICH"]
# primary_DT[incname == "METCALF" & state == "illinoi", incname := "METCALFE"]
# primary_DT[incname == "SCHROEDER.PATRICIA" & state == "colorad", incname := "SCHROEDER"]
# primary_DT[incname == "OBRIEN" & state == "illinoi", incname := "O'BRIEN"]
# primary_DT[incname == "FROELICH" & state == "wiscons", incname := "FROEHLICH"]
# primary_DT[incname == "DAMOURS" & state == "new ham", incname := "D'AMOURS"]
# primary_DT[incname == "CLAUSEN_DON_H." & state == "califor", incname := "CLAUSEN"]
# primary_DT[incname == "ATKISON" & state == "pennsyl", incname := "ATKINSON"]
# primary_DT[incname == "SCHAEFER" & state == "colorad" & year < 1996, incname := "SCHAFFER"]
# primary_DT[incname == "VISCLOSKEY" & state == "indiana", incname := "VISCLOSKY"]
# primary_DT[incname == "OAKER" & state == "ohio", incname := "OAKAR"]
# primary_DT[incname == "WOOLSLEY" & state == "califor", incname := "WOOLSEY"]
# primary_DT[incname == "SHERMAN" & stcd == 528 & year == 2002, incname := "BERMAN"]
# primary_DT[incname == "SHERMAN" & stcd == 528 & year == 2004, incname := "BERMAN"]
# primary_DT[incname == "SHERMAN" & stcd == 528 & year == 2006, incname := "BERMAN"]
#
#
# primary_DT <- primary_DT[candidate != incname, ]
# save(primary_DT, file = "inst/extdata/primary_DT.RData")
load("inst/extdata/primary_DT.RData")



load("inst/extdata/house_covariates.RData")
